In [ ]:
!pip install cupy-cuda11x

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0/100.0 MB 8.8 MB/s eta 0:00:00


In [3]:
USE_GPU = False

if USE_GPU:
    import cupy as xp
else:
    import numpy as xp

# User Input
N = int(input("Enter size of vector/matrix (N): "))

# Input Vectors
print("Enter elements for Vector A:")
A = xp.array([int(input(f"A[{i}]: ")) for i in range(N)])
print("Enter elements for Vector B:")
B = xp.array([int(input(f"B[{i}]: ")) for i in range(N)])

# Vector Addition
C = A + B

print("\nVector A:", A)
print("Vector B:", B)
print("Addition (A + B):", C)

# Input Matrices
print("\nEnter elements for Matrix D:")
D = xp.zeros((N, N), dtype=int)
for i in range(N):
    for j in range(N):
        D[i, j] = int(input(f"D[{i}][{j}]: "))

print("Enter elements for Matrix E:")
E = xp.zeros((N, N), dtype=int)
for i in range(N):
    for j in range(N):
        E[i, j] = int(input(f"E[{i}][{j}]: "))

# Matrix Multiplication
F = D @ E

print("\nMatrix D:")
print(D)

print("\nMatrix E:")
print(E)

print("\nMultiplication Result (D x E):")
print(F)

Enter size of vector/matrix (N): 2
Enter elements for Vector A:
A[0]: 2
A[1]: 5
Enter elements for Vector B:
B[0]: 4
B[1]: 3

Vector A: [2 5]
Vector B: [4 3]
Addition (A + B): [6 8]

Enter elements for Matrix D:
D[0][0]: 1
D[0][1]: 5
D[1][0]: 2
D[1][1]: 3
Enter elements for Matrix E:
E[0][0]: 5
E[0][1]: 8
E[1][0]: 3
E[1][1]: 1

Matrix D:
[[1 5]
 [2 3]]

Matrix E:
[[5 8]
 [3 1]]

Multiplication Result (D x E):
[[20 13]
 [19 19]]
